import { eq } from 'drizzle-orm';
import { db, withOrgContext } from '@/db/client';
import { dashboards } from '@/db/schema';
import { validatePrintToken } from './print-token';

export type PrintDashboardResult =
  | { status: 'unauthorized' }
  | { status: 'not_found' }
  | {
      status: 'ok';
      dashboard: {
        id: string;
        orgId: string;
        title: string;
        description: string | null;
        theme: string;
        widgets: unknown[];
      };
    };

/**
 * Resolve a one-time print token to a dashboard.
 *
 * The token must have been generated by generatePrintToken() and is
 * single-use: validatePrintToken deletes the key on successful read.
 */
export async function getPrintDashboard(token: string): Promise<PrintDashboardResult> {
  const payload = await validatePrintToken(token);
  if (!payload) return { status: 'unauthorized' };

  const dashboard = await withOrgContext(payload.orgId, null, async () => {
    const row = await db.query.dashboards.findFirst({
      where: eq(dashboards.id, payload.dashboardId),
    });
    return row;
  });

  if (!dashboard) return { status: 'not_found' };

  return {
    status: 'ok',
    dashboard: {
      id: dashboard.id,
      orgId: dashboard.orgId,
      title: dashboard.title,
      description: dashboard.description ?? null,
      theme: dashboard.theme,
      widgets: Array.isArray(dashboard.widgets) ? dashboard.widgets : [],
    },
  };
}