import type { DashboardTemplate } from './types';

export const TEMPLATE_CATALOG: DashboardTemplate[] = [
  {
    id: 'saas-mrr-analytics',
    name: 'SaaS MRR & Retención',
    description: 'KPIs clave para startups SaaS: MRR, ARR, Churn rate, ARPU y retención de suscriptores.',
    category: 'saas',
    icon: 'TrendingUp',
    theme: 'moderno-saas',
    archetype: 'kpi-grid',
    density: 'balanced',
    recommendedSourceTypes: ['stripe', 'postgres'],
    widgets: [
      {
        id: 'w_kpi_mrr',
        type: 'kpi',
        position: { col: 1, row: 1, colSpan: 3, rowSpan: 1 },
        config: { title: 'MRR (Ingreso Mensual Recurrente)', format: 'currency' },
        data: { value: 42850, delta: 12.4, previousValue: 38120 },
        source: { kind: 'query', dataSourceId: 'demo-source', query: { kind: 'sql', sql: 'SELECT mrr FROM stats' } },
      },
      {
        id: 'w_kpi_arr',
        type: 'kpi',
        position: { col: 4, row: 1, colSpan: 3, rowSpan: 1 },
        config: { title: 'ARR Proyectado', format: 'currency' },
        data: { value: 514200, delta: 12.4, previousValue: 457440 },
        source: { kind: 'query', dataSourceId: 'demo-source', query: { kind: 'sql', sql: 'SELECT arr FROM stats' } },
      },
      {
        id: 'w_kpi_churn',
        type: 'kpi',
        position: { col: 7, row: 1, colSpan: 3, rowSpan: 1 },
        config: { title: 'Tasa de Churn Mensual', format: 'percent' },
        data: { value: 2.1, delta: -0.4, previousValue: 2.5 },
        source: { kind: 'query', dataSourceId: 'demo-source', query: { kind: 'sql', sql: 'SELECT churn FROM stats' } },
      },
      {
        id: 'w_kpi_arpu',
        type: 'kpi',
        position: { col: 10, row: 1, colSpan: 3, rowSpan: 1 },
        config: { title: 'ARPU Promedio', format: 'currency' },
        data: { value: 85.5, delta: 4.2, previousValue: 82.0 },
        source: { kind: 'query', dataSourceId: 'demo-source', query: { kind: 'sql', sql: 'SELECT arpu FROM stats' } },
      },
      {
        id: 'w_chart_mrr_trend',
        type: 'line-chart',
        position: { col: 1, row: 2, colSpan: 12, rowSpan: 3 },
        config: { title: 'Evolución de MRR vs Nuevos Suscriptores', xAxis: 'category' },
        data: [
          { mes: 'Ene', mrr: 28000 },
          { mes: 'Feb', mrr: 31500 },
          { mes: 'Mar', mrr: 34200 },
          { mes: 'Abr', mrr: 37800 },
          { mes: 'May', mrr: 39100 },
          { mes: 'Jun', mrr: 42850 },
        ],
        source: { kind: 'query', dataSourceId: 'demo-source', query: { kind: 'sql', sql: 'SELECT mes, mrr FROM monthly_mrr' } },
      },
    ],
  },
  {
    id: 'ecommerce-revenue',
    name: 'E-Commerce Venta & Productos',
    description: 'Ventas totales, ticket promedio, unidades vendidas y desglose de top productos por categoría.',
    category: 'ecommerce',
    icon: 'ShoppingCart',
    theme: 'moderno-saas',
    archetype: 'hero-focus',
    density: 'balanced',
    recommendedSourceTypes: ['postgres', 'spreadsheet', 'sheets'],
    widgets: [
      {
        id: 'w_hero_sales',
        type: 'kpi',
        position: { col: 1, row: 1, colSpan: 6, rowSpan: 2 },
        config: { title: 'Ventas Totales del Mes', format: 'currency' },
        data: { value: 128400, delta: 18.2, previousValue: 108600 },
        source: { kind: 'query', dataSourceId: 'demo-source', query: { kind: 'sql', sql: 'SELECT sum(total) FROM orders' } },
      },
      {
        id: 'w_kpi_aov',
        type: 'kpi',
        position: { col: 7, row: 1, colSpan: 2, rowSpan: 2 },
        config: { title: 'Ticket Promedio (AOV)', format: 'currency' },
        data: { value: 64.2, delta: 3.5, previousValue: 62.0 },
        source: { kind: 'query', dataSourceId: 'demo-source', query: { kind: 'sql', sql: 'SELECT avg(total) FROM orders' } },
      },
      {
        id: 'w_kpi_orders',
        type: 'kpi',
        position: { col: 9, row: 1, colSpan: 2, rowSpan: 2 },
        config: { title: 'Órdenes Procesadas', format: 'number' },
        data: { value: 2000, delta: 14.1, previousValue: 1752 },
        source: { kind: 'query', dataSourceId: 'demo-source', query: { kind: 'sql', sql: 'SELECT count(*) FROM orders' } },
      },
      {
        id: 'w_kpi_items',
        type: 'kpi',
        position: { col: 11, row: 1, colSpan: 2, rowSpan: 2 },
        config: { title: 'Artículos Vendidos', format: 'number' },
        data: { value: 5840, delta: 9.8, previousValue: 5318 },
        source: { kind: 'query', dataSourceId: 'demo-source', query: { kind: 'sql', sql: 'SELECT sum(items) FROM orders' } },
      },
      {
        id: 'w_chart_products',
        type: 'line-chart',
        position: { col: 1, row: 3, colSpan: 12, rowSpan: 3 },
        config: { title: 'Tendencia Semanal de Ventas', xAxis: 'category' },
        data: [
          { semana: 'Sem 1', ventas: 28200 },
          { semana: 'Sem 2', ventas: 31400 },
          { semana: 'Sem 3', ventas: 34500 },
          { semana: 'Sem 4', ventas: 34300 },
        ],
        source: { kind: 'query', dataSourceId: 'demo-source', query: { kind: 'sql', sql: 'SELECT semana, sum(total) FROM orders GROUP BY semana' } },
      },
    ],
  },
  {
    id: 'marketing-roi',
    name: 'Marketing ROI & Canales',
    description: 'Gasto publicitario, CAC, conversiones por canal de adquisición y retorno de inversión en Ads.',
    category: 'marketing',
    icon: 'Megaphone',
    theme: 'moderno-saas',
    archetype: 'growth-metrics',
    density: 'balanced',
    recommendedSourceTypes: ['sheets', 'spreadsheet', 'postgres'],
    widgets: [
      {
        id: 'w_chart_channels',
        type: 'bar-chart',
        position: { col: 1, row: 1, colSpan: 6, rowSpan: 3 },
        config: { title: 'Canales de Adquisición', xAxis: 'category' },
        data: [
          { canal: 'Google Ads', leads: 580 },
          { canal: 'Meta Ads', leads: 420 },
          { canal: 'SEO', leads: 270 },
        ],
        source: { kind: 'query', dataSourceId: 'demo-source', query: { kind: 'sql', sql: 'SELECT canal, leads FROM marketing' } },
      },
      {
        id: 'w_chart_retention',
        type: 'line-chart',
        position: { col: 7, row: 1, colSpan: 6, rowSpan: 3 },
        config: { title: 'Curva de Retención de Campañas', xAxis: 'category' },
        data: [
          { dia: 'D1', retencion: 85 },
          { dia: 'D7', retencion: 62 },
          { dia: 'D30', retencion: 44 },
        ],
        source: { kind: 'query', dataSourceId: 'demo-source', query: { kind: 'sql', sql: 'SELECT dia, retencion FROM retention' } },
      },
      {
        id: 'w_chart_cohorts',
        type: 'bar-chart',
        position: { col: 1, row: 4, colSpan: 6, rowSpan: 3 },
        config: { title: 'Comportamiento por Cohorte', xAxis: 'category' },
        data: [
          { cohorte: 'Q1', valor: 120 },
          { cohorte: 'Q2', valor: 145 },
        ],
        source: { kind: 'query', dataSourceId: 'demo-source', query: { kind: 'sql', sql: 'SELECT cohorte, valor FROM cohorts' } },
      },
      {
        id: 'w_chart_ltv',
        type: 'bar-chart',
        position: { col: 7, row: 4, colSpan: 6, rowSpan: 3 },
        config: { title: 'Distribución de LTV', xAxis: 'category' },
        data: [
          { segmento: 'Básico', ltv: 320 },
          { segmento: 'Pro', ltv: 850 },
        ],
        source: { kind: 'query', dataSourceId: 'demo-source', query: { kind: 'sql', sql: 'SELECT segmento, ltv FROM ltv_stats' } },
      },
      {
        id: 'w_kpi_cac',
        type: 'kpi',
        position: { col: 1, row: 7, colSpan: 4, rowSpan: 1 },
        config: { title: 'CAC Promedio', format: 'currency' },
        data: { value: 42.5, delta: -8.1, previousValue: 46.25 },
        source: { kind: 'query', dataSourceId: 'demo-source', query: { kind: 'sql', sql: 'SELECT cac FROM marketing' } },
      },
      {
        id: 'w_kpi_roas',
        type: 'kpi',
        position: { col: 5, row: 7, colSpan: 4, rowSpan: 1 },
        config: { title: 'ROAS Global', format: 'number' },
        data: { value: 4.8, delta: 0.6, previousValue: 4.2 },
        source: { kind: 'query', dataSourceId: 'demo-source', query: { kind: 'sql', sql: 'SELECT roas FROM marketing' } },
      },
      {
        id: 'w_kpi_conversions',
        type: 'kpi',
        position: { col: 9, row: 7, colSpan: 4, rowSpan: 1 },
        config: { title: 'Conversiones Totales', format: 'number' },
        data: { value: 1420, delta: 15.0, previousValue: 1235 },
        source: { kind: 'query', dataSourceId: 'demo-source', query: { kind: 'sql', sql: 'SELECT count(*) FROM leads' } },
      },
    ],
  },
  {
    id: 'financial-pnl',
    name: 'Reporte Financiero P&L',
    description: 'Estado de pérdidas y ganancias, margen operativo, gastos fijos/variables y flujo de caja libre.',
    category: 'finance',
    icon: 'DollarSign',
    theme: 'corporate',
    archetype: 'finance-report',
    density: 'dense',
    recommendedSourceTypes: ['postgres', 'spreadsheet'],
    widgets: [
      {
        id: 'w_kpi_net_income',
        type: 'kpi',
        position: { col: 1, row: 1, colSpan: 3, rowSpan: 1 },
        config: { title: 'Utilidad Neta del Período', format: 'currency' },
        data: { value: 68400, delta: 8.5, previousValue: 63040 },
        source: { kind: 'query', dataSourceId: 'demo-source', query: { kind: 'sql', sql: 'SELECT net_income FROM financial_summary' } },
      },
      {
        id: 'w_kpi_margin',
        type: 'kpi',
        position: { col: 4, row: 1, colSpan: 3, rowSpan: 1 },
        config: { title: 'Margen Operativo Ebitda', format: 'percent' },
        data: { value: 34.2, delta: 1.2, previousValue: 33.0 },
        source: { kind: 'query', dataSourceId: 'demo-source', query: { kind: 'sql', sql: 'SELECT margin FROM financial_summary' } },
      },
      {
        id: 'w_kpi_revenue',
        type: 'kpi',
        position: { col: 7, row: 1, colSpan: 3, rowSpan: 1 },
        config: { title: 'Ingresos Brutos', format: 'currency' },
        data: { value: 210000, delta: 16.6, previousValue: 180000 },
        source: { kind: 'query', dataSourceId: 'demo-source', query: { kind: 'sql', sql: 'SELECT gross_revenue FROM financial_summary' } },
      },
      {
        id: 'w_kpi_opex',
        type: 'kpi',
        position: { col: 10, row: 1, colSpan: 3, rowSpan: 1 },
        config: { title: 'Gastos Operativos OPEX', format: 'currency' },
        data: { value: 68000, delta: -9.6, previousValue: 62000 },
        source: { kind: 'query', dataSourceId: 'demo-source', query: { kind: 'sql', sql: 'SELECT opex FROM financial_summary' } },
      },
      {
        id: 'w_chart_breakdown',
        type: 'bar-chart',
        position: { col: 1, row: 2, colSpan: 6, rowSpan: 4 },
        config: { title: 'Desglose de Gastos Operativos', xAxis: 'category' },
        data: [
          { categoria: 'Nómina', monto: 38000 },
          { categoria: 'Software / Infra', monto: 12000 },
          { categoria: 'Marketing', monto: 11000 },
          { categoria: 'Oficina', monto: 7000 },
        ],
        source: { kind: 'query', dataSourceId: 'demo-source', query: { kind: 'sql', sql: 'SELECT categoria, monto FROM opex_breakdown' } },
      },
      {
        id: 'w_table_pnl',
        type: 'table',
        position: { col: 7, row: 2, colSpan: 6, rowSpan: 4 },
        config: {
          title: 'Detalle General de Líneas de P&L',
          columns: [
            { key: 'concepto', label: 'Concepto' },
            { key: 'q1', label: 'Q1' },
            { key: 'q2', label: 'Q2' },
            { key: 'var', label: 'Variación' },
          ],
        },
        data: [
          { concepto: 'Ingresos Brutos', q1: 180000, q2: 210000, var: '+16.6%' },
          { concepto: 'Costo de Ventas (COGS)', q1: -54000, q2: -61000, var: '+12.9%' },
          { concepto: 'Utilidad Bruta', q1: 126000, q2: 149000, var: '+18.25%' },
          { concepto: 'Gastos Operativos (OPEX)', q1: -62000, q2: -68000, var: '+9.6%' },
          { concepto: 'Resultado Neto Final', q1: 64000, q2: 81000, var: '+26.5%' },
        ],
        source: { kind: 'query', dataSourceId: 'demo-source', query: { kind: 'sql', sql: 'SELECT * FROM pnl_report' } },
      },
    ],
  },
  {
    id: 'ops-monitoring',
    name: 'Monitoreo de Operaciones & SLA',
    description: 'Estado de infraestructura, uptime de APIs, latencia p95 y tasa de error de peticiones.',
    category: 'operations',
    icon: 'Activity',
    theme: 'corporate',
    archetype: 'operations-live',
    density: 'balanced',
    recommendedSourceTypes: ['postgres'],
    widgets: [
      {
        id: 'w_kpi_uptime',
        type: 'kpi',
        position: { col: 1, row: 1, colSpan: 3, rowSpan: 1 },
        config: { title: 'Disponibilidad de Servicio (SLA)', format: 'percent' },
        data: { value: 99.98, delta: 0.01, previousValue: 99.97 },
        source: { kind: 'query', dataSourceId: 'demo-source', query: { kind: 'sql', sql: 'SELECT uptime FROM system_health' } },
      },
      {
        id: 'w_kpi_latency',
        type: 'kpi',
        position: { col: 4, row: 1, colSpan: 3, rowSpan: 1 },
        config: { title: 'Latencia p95 (ms)', format: 'number' },
        data: { value: 142, delta: -12.0, previousValue: 154 },
        source: { kind: 'query', dataSourceId: 'demo-source', query: { kind: 'sql', sql: 'SELECT latency FROM system_health' } },
      },
      {
        id: 'w_kpi_error_rate',
        type: 'kpi',
        position: { col: 7, row: 1, colSpan: 3, rowSpan: 1 },
        config: { title: 'Tasa de Error HTTP 5xx', format: 'percent' },
        data: { value: 0.04, delta: -0.01, previousValue: 0.05 },
        source: { kind: 'query', dataSourceId: 'demo-source', query: { kind: 'sql', sql: 'SELECT error_rate FROM system_health' } },
      },
      {
        id: 'w_kpi_rps',
        type: 'kpi',
        position: { col: 10, row: 1, colSpan: 3, rowSpan: 1 },
        config: { title: 'Peticiones / seg (RPS)', format: 'number' },
        data: { value: 480, delta: 25.0, previousValue: 384 },
        source: { kind: 'query', dataSourceId: 'demo-source', query: { kind: 'sql', sql: 'SELECT rps FROM system_health' } },
      },
      {
        id: 'w_chart_latency',
        type: 'area-chart',
        position: { col: 1, row: 2, colSpan: 12, rowSpan: 3 },
        config: { title: 'Latencia de Peticiones en Tiempo Real', xAxis: 'category' },
        data: [
          { hora: '12:00', p95: 135 },
          { hora: '13:00', p95: 148 },
          { hora: '14:00', p95: 160 },
          { hora: '15:00', p95: 142 },
          { hora: '16:00', p95: 138 },
        ],
        source: { kind: 'query', dataSourceId: 'demo-source', query: { kind: 'sql', sql: 'SELECT hora, p95 FROM latency_logs' } },
      },
      {
        id: 'w_chart_target',
        type: 'line-chart',
        position: { col: 1, row: 5, colSpan: 6, rowSpan: 3 },
        config: { title: 'Comparativa Actual vs Objetivo', xAxis: 'category' },
        data: [
          { hora: '12:00', actual: 98 },
          { hora: '13:00', actual: 99 },
        ],
        source: { kind: 'query', dataSourceId: 'demo-source', query: { kind: 'sql', sql: 'SELECT hora, actual FROM ops_target' } },
      },
      {
        id: 'w_chart_sla',
        type: 'line-chart',
        position: { col: 7, row: 5, colSpan: 6, rowSpan: 3 },
        config: { title: 'Cumplimiento de SLA', xAxis: 'category' },
        data: [
          { hora: '12:00', sla: 99.9 },
          { hora: '13:00', sla: 99.98 },
        ],
        source: { kind: 'query', dataSourceId: 'demo-source', query: { kind: 'sql', sql: 'SELECT hora, sla FROM ops_sla' } },
      },
    ],
  },
];

export function getTemplateById(id: string): DashboardTemplate | undefined {
  return TEMPLATE_CATALOG.find((t) => t.id === id);
}

export function getTemplatesByCategory(category: string): DashboardTemplate[] {
  return TEMPLATE_CATALOG.filter((t) => t.category === category);
}
