import { describe, it, expect, beforeAll, beforeEach, afterAll } from 'vitest';
import { sql } from 'drizzle-orm';
import { getTestDb, resetDb, closeTestDb, type TestDb } from './postgres';

/**
 * Migration 0015 — RLS on `orgs`, by membership.
 *
 * `orgs` is the one tenant table that cannot use
 * `USING (id = app_current_org_id())`, and the reason is worth keeping here:
 * three legitimate code paths query it across orgs. Measured against a live
 * database with the naive policy, all three broke:
 *
 *   org switcher   saw 1 org instead of N
 *   signup          new row violates row-level security policy
 *   uniqueSlug      saw 0 orgs, so a new org collided with orgs_slug_idx
 *
 * The signup failure has a non-obvious cause: the org id is generated by the
 * database, so it is unknown until the row exists and an id-based policy
 * cannot match it. `provisionOrgForUser` now generates it in the app instead.
 *
 * The membership policy needs to read `org_members` from inside the policy,
 * which is recursive because `org_members` has its own RLS. Hence the
 * SECURITY DEFINER helper: it runs as the owner, so `org_members` RLS does not
 * apply inside it, and it does not read `orgs`, so there is no recursion.
 *
 * Requires Docker; skips — visibly, not as a pass — without a container
 * runtime, unless RLS_TESTS_REQUIRED=1.
 */
const RUNTIME_UNAVAILABLE = /container runtime|Could not find a working container runtime/i;

const USER_MEMBER = '33333333-3333-3333-3333-333333333333';
const USER_NEW = '44444444-4444-4444-4444-444444444444';
const USER_STRANGER = '55555555-5555-5555-5555-555555555555';
const ORG_A = '11111111-1111-1111-1111-111111111111';
const ORG_B = '22222222-2222-2222-2222-222222222222';
/** Any uuid: the insert policy only checks that a user id is set. */
const NO_ORG_YET = '00000000-0000-0000-0000-000000000001';

/**
 * Drizzle's postgres-js driver wraps every driver error in a
 * `DrizzleQueryError` whose `.message` is just `Failed query: <sql>`. The
 * PostgreSQL text — and the `severity_local` field that says ERROR — live in
 * the `cause`. So `rejects.toThrow(/row-level security/)` asserts against the
 * wrapper's string and fails on a rejection that was in fact the correct one.
 * Walks the chain and concatenates every message it finds.
 */
function errorText(error: unknown): string {
  const parts: string[] = [];
  let cursor: unknown = error;
  for (let depth = 0; cursor && depth < 10; depth += 1) {
    if (typeof cursor !== 'object') {
      parts.push(String(cursor));
      break;
    }
    const record = cursor as { message?: unknown; severity_local?: unknown; cause?: unknown };
    if (typeof record.message === 'string') parts.push(record.message);
    if (typeof record.severity_local === 'string') parts.push(record.severity_local);
    cursor = record.cause;
  }
  return parts.join(' | ');
}

describe('RLS on orgs, by membership', () => {
  let db: TestDb;
  let runtimeAvailable = false;

  beforeAll(async () => {
    try {
      db = await getTestDb();
      runtimeAvailable = true;
    } catch (error) {
      if (RUNTIME_UNAVAILABLE.test(String(error))) {
        if (process.env.RLS_TESTS_REQUIRED === '1') throw error;
        console.warn('[integration] skipped: no container runtime for Postgres');
        return;
      }
      throw error;
    }
  }, 120_000);

  afterAll(async () => {
    if (db) await closeTestDb();
  });

  beforeEach(async () => {
    if (db) await resetDb();
  }, 60_000);

  // Vitest only exposes ctx.skip() inside a test body, so availability is
  // checked per test. Without this the assertions return early and vitest
  // reports them PASSED — a green suite that verified nothing.
  function itWithDb(name: string, fn: () => Promise<void>): void {
    it(name, async (ctx) => {
      if (!runtimeAvailable || !db) {
        ctx.skip();
        return;
      }
      await fn();
    });
  }

  /** Seed as the migration role, so RLS does not filter the fixture itself. */
  async function seed(): Promise<void> {
    await db.execute(sql`INSERT INTO users (id, name, email) VALUES
      (${USER_MEMBER}, 'member', 'm@x.invalid'),
      (${USER_NEW}, 'new', 'n@x.invalid'),
      (${USER_STRANGER}, 'stranger', 's@x.invalid')`);
    await db.execute(sql`INSERT INTO orgs (id, name, slug) VALUES
      (${ORG_A}, 'Org A', 'org-a'),
      (${ORG_B}, 'Org B', 'org-b')`);
    await db.execute(sql`INSERT INTO org_members (org_id, user_id, role) VALUES
      (${ORG_A}, ${USER_MEMBER}, 'admin')`);
  }

  /** Run as the non-superuser app role, the way the app actually connects. */
  function asApp<T>(fn: (tx: TestDb) => Promise<T>, userId: string, orgId: string): Promise<T> {
    return db.transaction(async (tx) => {
      await tx.execute(sql.raw('SET LOCAL ROLE dashbi'));
      await tx.execute(
        sql`SELECT set_config('app.current_user_id', ${userId}, true),
                   set_config('app.current_org_id', ${orgId}, true)`,
      );
      return fn(tx as unknown as TestDb);
    });
  }

  itWithDb('is enabled and forced', async () => {
    const rows = await db.execute<{ relrowsecurity: boolean; relforcerowsecurity: boolean }>(sql`
      SELECT relrowsecurity, relforcerowsecurity FROM pg_class WHERE relname = 'orgs'
    `);
    expect(rows[0]?.relrowsecurity).toBe(true);
    expect(rows[0]?.relforcerowsecurity).toBe(true);
  });

  itWithDb('shows a member every org they belong to, and only those', async () => {
    await seed();
    const rows = await asApp(
      (tx) => tx.execute<{ name: string }>(sql`SELECT name FROM orgs ORDER BY name`),
      USER_MEMBER,
      ORG_A,
    );
    // The regression this whole migration exists to avoid: a naive
    // `id = app_current_org_id()` policy returns zero rows here, because the
    // user legitimately belongs to more than one org.
    expect(rows.map((r) => r.name)).toEqual(['Org A']);
  });

  itWithDb('shows nothing to a user who is not a member', async () => {
    await seed();
    const rows = await asApp(
      (tx) => tx.execute<{ n: number }>(sql`SELECT count(*)::int AS n FROM orgs`),
      USER_STRANGER,
      ORG_A,
    );
    expect(rows[0]?.n).toBe(0);
  });

  itWithDb('provisions an org the way config.ts does: id from the app, no RETURNING', async () => {
    await seed();
    // This mirrors `provisionOrgForUser` step for step. The org id comes from
    // the app and the INSERT has no RETURNING, because of the trap asserted
    // in the next test.
    const orgId = '66666666-6666-6666-6666-666666666666';
    const visible = await asApp(
      async (tx) => {
        await tx.execute(
          sql`INSERT INTO orgs (id, name, slug) VALUES (${orgId}, 'Nueva', 'nueva-1')`,
        );
        // Immediately after the insert the row is invisible to this session:
        // it has no membership yet, so orgs_read does not match it.
        const beforeMembership = await tx.execute<{ n: number }>(
          sql`SELECT count(*)::int AS n FROM orgs WHERE id = ${orgId}`,
        );
        expect(beforeMembership[0]?.n).toBe(0);

        await tx.execute(
          sql`INSERT INTO org_members (org_id, user_id, role) VALUES (${orgId}, ${USER_NEW}, 'admin')`,
        );

        // The moment the membership exists the org becomes readable — the
        // membership policy is what made it visible, not a bypass.
        return tx.execute<{ n: number }>(
          sql`SELECT count(*)::int AS n FROM orgs WHERE id = ${orgId}`,
        );
      },
      USER_NEW,
      NO_ORG_YET,
    );
    expect(visible[0]?.n).toBe(1);
  });

  itWithDb('refuses INSERT ... RETURNING on an org the session cannot yet read', async () => {
    await seed();
    // The trap that broke signup, measured rather than assumed. In PostgreSQL
    // `INSERT ... RETURNING` also evaluates the SELECT policy on the row it is
    // about to return, so asking for the id back is asking to read a row the
    // session has no membership for. The error message blames WITH CHECK
    // ("new row violates row-level security policy") and comes from
    // ExecWithCheckOptions, which sends you looking at the wrong policy.
    //
    // This is why config.ts generates the id in the app and drops RETURNING
    // rather than widening orgs_read with an id-based OR branch: the whole
    // point of this migration is that `orgs` is protected by membership, and
    // `USING (id = app_current_org_id())` is the id-based policy that broke
    // the org switcher in the first place.
    const err = await asApp(
      (tx) =>
        tx.execute<{ id: string }>(
          sql`INSERT INTO orgs (name, slug) VALUES ('Otra', 'otra-1') RETURNING id`,
        ),
      USER_NEW,
      NO_ORG_YET,
    ).then(
      () => null,
      (e: unknown) => e,
    );
    expect(errorText(err)).toMatch(/row-level security/i);
  });

  itWithDb('rejects an insert with no user context at all', async () => {
    await seed();
    const err = await db
      .transaction(async (tx) => {
        await tx.execute(sql.raw('SET LOCAL ROLE dashbi'));
        await tx.execute(
          sql`SELECT set_config('app.current_user_id', NULL, true),
                     set_config('app.current_org_id', ${ORG_A}, true)`,
        );
        return tx.execute(sql`INSERT INTO orgs (name, slug) VALUES ('Anon', 'anon-1')`);
      })
      .then(
        () => null,
        (e: unknown) => e,
      );
    expect(errorText(err)).toMatch(/row-level security/i);
  });

  itWithDb('rejects an insert when the user GUC is empty rather than erroring on the cast', async () => {
    await seed();
    // `current_setting('app.current_user_id', true)::uuid` on an empty-string
    // setting raises `invalid input syntax for type uuid: ""`, turning a
    // denial into a 500. Migration 0004 already fixed this for every other
    // policy; the two written here must not reintroduce it.
    const err = await db
      .transaction(async (tx) => {
        await tx.execute(sql.raw('SET LOCAL ROLE dashbi'));
        await tx.execute(
          sql`SELECT set_config('app.current_user_id', '', true),
                     set_config('app.current_org_id', ${ORG_A}, true)`,
        );
        return tx.execute(sql`INSERT INTO orgs (name, slug) VALUES ('Vacio', 'vacio-1')`);
      })
      .then(
        () => null,
        (e: unknown) => e,
      );
    expect(errorText(err)).toMatch(/row-level security/i);
    expect(errorText(err)).not.toMatch(/invalid input syntax/);
  });

  itWithDb('answers slug collisions globally, for a user in no org', async () => {
    await seed();
    // uniqueSlug used to query `orgs` directly. Under RLS the provisioning user
    // belongs to nobody yet, so it saw zero rows and happily picked a slug that
    // another org already held.
    const rows = await asApp(
      (tx) => tx.execute<{ taken: boolean; free: boolean }>(
        sql`SELECT dashbi_slug_is_taken('org-a') AS taken,
                   dashbi_slug_is_taken('nadie-lo-tiene') AS free`,
      ),
      USER_NEW,
      NO_ORG_YET,
    );
    expect(rows[0]?.taken).toBe(true);
    expect(rows[0]?.free).toBe(false);
  });

  itWithDb('keeps the membership helpers off PUBLIC and the AI role', async () => {
    const rows = await db.execute<{ proname: string; public_execute: boolean; ro_execute: boolean }>(sql`
      SELECT p.proname,
             has_function_privilege('public', p.oid, 'EXECUTE') AS public_execute,
             has_function_privilege('dashbi_readonly', p.oid, 'EXECUTE') AS ro_execute
      FROM pg_proc p JOIN pg_namespace n ON n.oid = p.pronamespace
      WHERE n.nspname = 'public'
        AND p.proname IN ('dashbi_user_belongs_to_org', 'dashbi_slug_is_taken')
    `);
    expect(rows.length).toBe(2);
    for (const row of rows) {
      expect(row.public_execute, `${row.proname} callable by PUBLIC`).toBe(false);
      expect(row.ro_execute, `${row.proname} callable by dashbi_readonly`).toBe(false);
    }
  });
});
